package pathcompiler

var WindowsOs = Specific{
	Name:                     "Windows",
	Description:              "all windows related os paths",
	Url:                      "",
	SpecificPathFileLocation: windowsProductionDefault + DefaultSuffix.SpecificPathFileLocation,
	VarAppRoot:               windowsProductionDefault,
	EtcAppRoot:               windowsProductionDefault,
	EtcAppConfigRoot:         windowsProductionDefault + DefaultSuffix.EtcAppConfigRoot,
	AppDbRoot:                windowsProductionDefault + DefaultSuffix.AppDbRoot,
	TempRoot:                 TempAppRoot,
	UserTempRoot:             TempAppRoot + DefaultSuffix.UserTempRoot,
	CacheTempRoot:            TempAppRoot + DefaultSuffix.CacheTempRoot,
	InstructionTempRoot:      TempAppRoot + DefaultSuffix.InstructionTempRoot,
	MigrationCacheRoot:       TempAppRoot + DefaultSuffix.MigrationCacheRoot,
	PackageTempRoot:          TempAppRoot + DefaultSuffix.PackageTempRoot,
	LogAppRoot:               windowsProductionDefault + "\\logs",
	VarCacheRoot:             windowsProductionDefault + DefaultSuffix.VarCacheRoot,
	DownloadsRoot:            windowsProductionDefault + DefaultSuffix.DownloadsRoot,
	ScriptsRoot:              windowsProductionDefault + DefaultSuffix.ScriptsRoot,
	DecompressRoot:           TempAppRoot + DefaultSuffix.DecompressRoot,
	PackagesRoot:             windowsProductionDefault + DefaultSuffix.PackagesRoot,
	PackagesDownloadRoot:     windowsProductionDefault + DefaultSuffix.PackagesDownloadRoot,
	DefaultInstructionsRoot:  windowsProductionDefault + DefaultSuffix.DefaultInstructionsRoot,
	DefaultEnvRoot:           windowsProductionDefault + DefaultSuffix.DefaultEnvRoot,
	DefaultEnvPathRoot:       windowsProductionDefault + DefaultSuffix.DefaultEnvPathRoot,
	BackupRoot:               windowsProductionDefault + DefaultSuffix.BackupRoot,
	ArchiveRoot:              windowsProductionDefault + DefaultSuffix.ArchiveRoot,
	ZipsRoot:                 windowsProductionDefault + DefaultSuffix.ZipsRoot,
	DefaultConfigFilePath:    windowsProductionDefault + DefaultSuffix.DefaultConfigFilePath,
}
