package pathcompilertests

import (
	"reflect"

	"gitlab.com/auk-go/core/coreimpl/enumimpl"
	"gitlab.com/auk-go/core/coretests"
	"gitlab.com/auk-go/enum/osmixtype"
)

var pathCompilerTestCases = []TestWrapper{
	{
		SelectBy:          osmixtype.Unix,
		NameAssert:        "Unix",
		DescriptionAssert: "all unix(ubuntu, debian, linux, darwin ...) related os paths",
		RunsIn: []osmixtype.Variant{
			osmixtype.Windows,
		},
		BaseTestCase: coretests.BaseTestCase{
			Title:        "Unix, Ubuntu, Linux Path should match as per expectation map",
			ArrangeInput: nil,
			ActualInput:  nil,
			ExpectedInput: enumimpl.DynamicMap(map[string]interface{}{
				"AppDbRoot":                "/var/opt/{app-name}/databases/",
				"ArchiveRoot":              "/var/opt/{app-name}/archived/",
				"BackupRoot":               "/var/opt/{app-name}/backups/",
				"CacheTempRoot":            `c:\Windows\Temp\{app-name}/cache/`,
				"DecompressRoot":           `c:\Windows\Temp\{app-name}/decompress/`,
				"DefaultConfigFilePath":    "/etc/{app-name}/config/default-config.json",
				"DefaultEnvPathRoot":       "/var/opt/{app-name}/env-paths/",
				"DefaultEnvRoot":           "/var/opt/{app-name}/env/",
				"DefaultInstructionsRoot":  "/var/opt/{app-name}/instructions/",
				"Description":              "all unix(ubuntu, debian, linux, darwin ...) related os paths",
				"DownloadsRoot":            "/var/opt/{app-name}/downloads/",
				"EtcAppConfigRoot":         "/etc/{app-name}/config",
				"EtcAppRoot":               "/etc/{app-name}",
				"InstructionTempRoot":      `c:\Windows\Temp\{app-name}/instructions/`,
				"LogAppRoot":               "/var/log/{app-name}",
				"MigrationCacheRoot":       `c:\Windows\Temp\{app-name}/migration-cache/`,
				"Name":                     "Unix",
				"PackageTempRoot":          `c:\Windows\Temp\{app-name}/packages/`,
				"PackagesDownloadRoot":     `/var/opt/{app-name}/packages-downloaded/`,
				"PackagesRoot":             "/etc/{app-name}/packages/",
				"PublicRoot":               "/var/www/",
				"ScriptsRoot":              "/var/opt/{app-name}/scripts/",
				"SnapshotsRoot":            "/var/opt/{app-name}-snapshots/",
				"SpecificPathFileLocation": "/var/opt/{app-name}/defined-paths/paths.json",
				"SslRoot":                  "/var/opt/{app-name}-ssl/",
				"TempRoot":                 `c:\Windows\Temp\{app-name}`,
				"UserTempRoot":             `c:\Windows\Temp\{app-name}/users/`,
				"VarAppRoot":               "/var/opt/{app-name}",
				"VarCacheRoot":             "/var/opt/{app-name}/cache/",
				"ZipsRoot":                 `/var/opt/{app-name}/compressed/`,
			}),
			ExpectedTypeOfExpected: reflect.TypeOf(enumimpl.DynamicMap{}),
		},
	},
	{
		RunsIn: []osmixtype.Variant{
			osmixtype.Unix,
		},
		SelectBy:          osmixtype.Unix,
		NameAssert:        "Unix",
		DescriptionAssert: "all unix(ubuntu, debian, linux, darwin ...) related os paths",
		BaseTestCase: coretests.BaseTestCase{
			Title:        "Unix, Ubuntu, Linux Path should match as per expectation map",
			ArrangeInput: nil,
			ActualInput:  nil,
			ExpectedInput: enumimpl.DynamicMap(map[string]interface{}{
				"AppDbRoot":                "/var/opt/{app-name}/databases/",
				"ArchiveRoot":              "/var/opt/{app-name}/archived/",
				"BackupRoot":               "/var/opt/{app-name}/backups/",
				"CacheTempRoot":            "/var/tmp/{app-name}/cache/",
				"DecompressRoot":           "/var/tmp/{app-name}/decompress/",
				"DefaultConfigFilePath":    "/etc/{app-name}/config/default-config.json",
				"DefaultEnvPathRoot":       "/var/opt/{app-name}/env-paths/",
				"DefaultEnvRoot":           "/var/opt/{app-name}/env/",
				"DefaultInstructionsRoot":  "/var/opt/{app-name}/instructions/",
				"Description":              "all unix(ubuntu, debian, linux, darwin ...) related os paths",
				"DownloadsRoot":            "/var/opt/{app-name}/downloads/",
				"EtcAppConfigRoot":         "/etc/{app-name}/config",
				"EtcAppRoot":               "/etc/{app-name}",
				"InstructionTempRoot":      "/var/tmp/{app-name}/instructions/",
				"LogAppRoot":               "/var/log/{app-name}",
				"MigrationCacheRoot":       "/var/tmp/{app-name}/migration-cache/",
				"Name":                     "Unix",
				"PackageTempRoot":          "/var/tmp/{app-name}/packages/",
				"PackagesDownloadRoot":     `/var/opt/{app-name}/packages-downloaded/`,
				"PackagesRoot":             "/etc/{app-name}/packages/",
				"PublicRoot":               "/var/www/",
				"ScriptsRoot":              "/var/opt/{app-name}/scripts/",
				"SnapshotsRoot":            "/var/opt/{app-name}-snapshots/",
				"SpecificPathFileLocation": "/var/opt/{app-name}/defined-paths/paths.json",
				"SslRoot":                  "/var/opt/{app-name}-ssl/",
				"TempRoot":                 "/var/tmp/{app-name}",
				"UserTempRoot":             "/var/tmp/{app-name}/users/",
				"VarAppRoot":               "/var/opt/{app-name}",
				"VarCacheRoot":             "/var/opt/{app-name}/cache/",
				"ZipsRoot":                 `/var/opt/{app-name}/compressed/`,
			}),
			ExpectedTypeOfExpected: reflect.TypeOf(enumimpl.DynamicMap{}),
		},
	},
	{
		RunsIn: []osmixtype.Variant{
			osmixtype.Unix,
		},
		IsTestEnv:         true,
		SelectBy:          osmixtype.Unix,
		NameAssert:        "AnyOs Test",
		DescriptionAssert: "all os test paths",
		BaseTestCase: coretests.BaseTestCase{
			Title:        "Test Env - Unix, Ubuntu, Linux Path should match as per expectation map",
			ArrangeInput: nil,
			ActualInput:  nil,
			ExpectedInput: enumimpl.DynamicMap(map[string]interface{}{
				"AppDbRoot":                "/tmp/{app-name}-test-env/databases/",
				"ArchiveRoot":              "/tmp/{app-name}-test-env/archived/",
				"BackupRoot":               "/tmp/{app-name}-test-env/backups/",
				"CacheTempRoot":            "/tmp/{app-name}-test-env/tmp/cache/",
				"DecompressRoot":           "/tmp/{app-name}-test-env/decompress/",
				"DefaultConfigFilePath":    "/tmp/{app-name}-test-env/config/default-config.json",
				"DefaultEnvPathRoot":       "/tmp/{app-name}-test-env/env-paths/",
				"DefaultEnvRoot":           "/tmp/{app-name}-test-env/env/",
				"DefaultInstructionsRoot":  "/tmp/{app-name}-test-env/instructions/",
				"Description":              "all os test paths",
				"DownloadsRoot":            "/tmp/{app-name}-test-env/var/opt//downloads/",
				"EtcAppConfigRoot":         "/tmp/{app-name}-test-env/etc/config",
				"EtcAppRoot":               "/tmp/{app-name}-test-env/etc/",
				"InstructionTempRoot":      "/tmp/{app-name}-test-env/tmp//instructions/",
				"LogAppRoot":               "/tmp/{app-name}-test-env/var/log/",
				"MigrationCacheRoot":       "/tmp/{app-name}-test-env/tmp//migration-cache/",
				"Name":                     "AnyOs Test",
				"PackageTempRoot":          "/tmp/{app-name}-test-env/tmp//packages/",
				"PackagesDownloadRoot":     "/tmp/{app-name}-test-env/packages-downloaded/",
				"PackagesRoot":             "/tmp/{app-name}-test-env/packages/",
				"PublicRoot":               "/tmp/{app-name}-test-env/var/www/",
				"ScriptsRoot":              "/tmp/{app-name}-test-env/scripts/",
				"SnapshotsRoot":            "/tmp/{app-name}-test-env/all-snapshots/",
				"SpecificPathFileLocation": "/tmp/{app-name}-test-env/defined-paths/paths.json",
				"SslRoot":                  "/tmp/{app-name}-test-env/all-ssl/",
				"TempRoot":                 "/tmp/{app-name}-test-env/tmp/",
				"UserTempRoot":             "/tmp/{app-name}-test-env/tmp//users/",
				"VarAppRoot":               "/tmp/{app-name}-test-env",
				"VarCacheRoot":             "/tmp/{app-name}-test-env/var/opt//cache/",
				"ZipsRoot":                 "/tmp/{app-name}-test-env/compressed/",
			}),
			ExpectedTypeOfExpected: reflect.TypeOf(enumimpl.DynamicMap{}),
		},
	},
	{
		RunsIn: []osmixtype.Variant{
			osmixtype.Windows,
		},
		IsTestEnv:         true,
		SelectBy:          osmixtype.Windows,
		NameAssert:        "AnyOs Test",
		DescriptionAssert: "all os test paths",
		BaseTestCase: coretests.BaseTestCase{
			Title:                  "Test Env - Windows Path should match as per expectation map",
			ArrangeInput:           nil,
			ActualInput:            nil,
			ExpectedInput:          enumimpl.DynamicMap(map[string]interface{}{}),
			ExpectedTypeOfExpected: reflect.TypeOf(enumimpl.DynamicMap{}),
		},
	},
}
